# Prometheus configuration to scrape metrics from the backend server
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mern-backend'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: /metrics
