name: Node.js CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js \${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      working-directory: ./opportunity_organiser_mern/backend
      run: npm install

    - name: Run backend tests
      working-directory: ./opportunity_organiser_mern/backend
      run: npm test

    - name: Install frontend dependencies
      working-directory: ./opportunity_organiser_mern/frontend
      run: npm install

    - name: Build frontend
      working-directory: ./opportunity_organiser_mern/frontend
      run: npm run build

    - name: Run frontend tests
      working-directory: ./opportunity_organiser_mern/frontend
      run: npm test -- --watchAll=false
